### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by Sergej-Popov** [drdreo/lit-scss-loader#1]
Are you planning on publishing it as an NPM in the nearest time? Thanks for this!

**Comment by drdreo** [comment]
It's in such an early state, i didn't want to publish it yet. But after some testing, it really works fine so far.
When i've removed some unnecessary dependencies, i might publish it.

Thanks for your interest. Love it.

**Comment by drdreo** [comment]
https://www.npmjs.com/package/lit-scss-loader

there you go

**Comment by Sergej-Popov** [comment]
Awesome, thank you!
