### ISSUE TITLE
Include documentation for use in es5 / legacy browsers

### ISSUE THREAD

**Issue by LambyPants** [drdreo/lit-scss-loader#3]
Hi,

Really like this package - it made our lives much easier when looking support scss in lit. Thanks for your contribution!

Just a suggestion, as I recently spent a few hours trying to add ie11 support to a lit-based project; ended up discovering it was the `extract-loader` in this package which was converting `scss -> js` and was being ignored by our `babel-loader`. It was particularly confusing because older browsers give no context to the error and just shows a lit-element css.ts file (which I assume is being imported in `templateGenerator.js` via `generateCSSImport`) as being the cause of the issue.

Normally your babel-loader config looks something like this:

```
    module: {
      rules: [
        {
          test: /\.js$|\.ts$/,
          use: {
            loader: 'babel-loader',
....
```

Was able to resolve the issue by simply doing the following

```
    module: {
      rules: [
        {
          test: /\.js$|\.ts$|\.s(c|a)ss$/,
          use: {
            loader: 'babel-loader',
```

There might be other ways to do this, but it def could save future users some time if they are using with tools like babel. Thanks!

**Comment by drdreo** [comment]
I am glad that someone can make use of it.
Thanks for the hint. I added a new section to the readme, mentioning the missing legacy support and linked to your solution.
