### ISSUE TITLE
Warning with new Lit

### ISSUE THREAD

**Issue by xiki808** [drdreo/lit-scss-loader#30]
With the new [Lit](https://lit.dev/) I'm getting `The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.` warning.

To update to new lit I have this in my package.json:

`
    "lit": "^2.0.0-rc.1",
    "lit-element": "^3.0.0-rc.1",
`

**Comment by krispy1298** [comment]
PR submittedd

**Comment by drdreo** [comment]
Thanks for the PR. I have reviewed and merged it!
